version: "3.7"
services:
  web:
    image: nginx:1.21
    ports:
      - 8000:80
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - php-fpm
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-fpm/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:cached
  composer:
    image: composer
    volumes:
      - ./:/app:cached
    working_dir: /app
